[general]
live_config_reload = true

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.85
blur = true

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
size = 14
builtin_box_drawing = false

[colors.primary]
foreground = "#eeeeee"
background = "#101010"

[colors.normal]
black = "#000000"
red = "#ee6666"
green = "#55aa44"
yellow = "#e5c07b"
blue = "#327cc7"
magenta = "#cc77dd"
cyan = "#55bbbb"
white = "#dcdef4"

[colors.bright]
black = "#5c5c6e"
red = "#e06c75"
green = "#98c379"
yellow = "#eecc77"
blue = "#77aaff"
magenta = "#dd88dd"
cyan = "#44cccc"
white = "#eeeeee"

[bell]
command = "beep"


